single_joint_actuator:
    # Publish all joint states -----------------------------------
    joints_update:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    joint_position_controller:
      type: position_controllers/JointPositionController
      joint: my_joint
